/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CatalogItemInput = IDL.Record({
  'stockStatus' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
  'mediaFiles' : IDL.Vec(ExternalBlob),
  'mediaTypes' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FilterOrders = IDL.Record({
  'status' : IDL.Opt(IDL.Text),
  'serviceType' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const OrderRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'instructions' : IDL.Text,
  'uploadedFiles' : IDL.Vec(ExternalBlob),
  'phone' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const CatalogItem = IDL.Record({
  'id' : IDL.Nat,
  'stockStatus' : IDL.Text,
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
  'mediaFiles' : IDL.Vec(ExternalBlob),
  'mediaTypes' : IDL.Vec(IDL.Text),
});
export const ShopOrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'itemId' : IDL.Nat,
  'itemName' : IDL.Text,
  'price' : IDL.Float64,
});
export const ShopOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'createdAt' : IDL.Int,
  'deliveryMethod' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'phone' : IDL.Text,
  'items' : IDL.Vec(ShopOrderItem),
});
export const BusinessInfo = IDL.Record({
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpiSettings = IDL.Record({
  'upiId' : IDL.Text,
  'qrCodeUrl' : IDL.Text,
});
export const ServiceOrder = IDL.Record({
  'files' : IDL.Vec(ExternalBlob),
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'instructions' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCatalogItem' : IDL.Func([CatalogItemInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCatalogItem' : IDL.Func([IDL.Nat], [], []),
  'filterOrders' : IDL.Func([FilterOrders], [IDL.Vec(OrderRecord)], ['query']),
  'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllCatalogItems' : IDL.Func([], [IDL.Vec(CatalogItem)], ['query']),
  'getAllShopOrders' : IDL.Func([], [IDL.Vec(ShopOrder)], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCatalogItem' : IDL.Func([IDL.Nat], [IDL.Opt(CatalogItem)], ['query']),
  'getCustomerProfile' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'customerName' : IDL.Text,
            'deliveryAddress' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getMyShopOrders' : IDL.Func([IDL.Text], [IDL.Vec(ShopOrder)], ['query']),
  'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(OrderRecord)], ['query']),
  'getPublishedCatalogItems' : IDL.Func([], [IDL.Vec(CatalogItem)], ['query']),
  'getUpiSettings' : IDL.Func([], [IDL.Opt(UpiSettings)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeShopOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ShopOrderItem),
        IDL.Float64,
      ],
      [ShopOrder],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCustomerProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setBusinessInfo' : IDL.Func([BusinessInfo], [], []),
  'setUpiSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitOrderFull' : IDL.Func([ServiceOrder], [IDL.Nat], []),
  'togglePublishCatalogItem' : IDL.Func([IDL.Nat], [], []),
  'updateCatalogItem' : IDL.Func([IDL.Nat, CatalogItemInput], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateShopOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CatalogItemInput = IDL.Record({
    'stockStatus' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
    'mediaFiles' : IDL.Vec(ExternalBlob),
    'mediaTypes' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FilterOrders = IDL.Record({
    'status' : IDL.Opt(IDL.Text),
    'serviceType' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const OrderRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'instructions' : IDL.Text,
    'uploadedFiles' : IDL.Vec(ExternalBlob),
    'phone' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const CatalogItem = IDL.Record({
    'id' : IDL.Nat,
    'stockStatus' : IDL.Text,
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
    'mediaFiles' : IDL.Vec(ExternalBlob),
    'mediaTypes' : IDL.Vec(IDL.Text),
  });
  const ShopOrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'itemId' : IDL.Nat,
    'itemName' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ShopOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'createdAt' : IDL.Int,
    'deliveryMethod' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'phone' : IDL.Text,
    'items' : IDL.Vec(ShopOrderItem),
  });
  const BusinessInfo = IDL.Record({
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpiSettings = IDL.Record({
    'upiId' : IDL.Text,
    'qrCodeUrl' : IDL.Text,
  });
  const ServiceOrder = IDL.Record({
    'files' : IDL.Vec(ExternalBlob),
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'instructions' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCatalogItem' : IDL.Func([CatalogItemInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCatalogItem' : IDL.Func([IDL.Nat], [], []),
    'filterOrders' : IDL.Func(
        [FilterOrders],
        [IDL.Vec(OrderRecord)],
        ['query'],
      ),
    'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllCatalogItems' : IDL.Func([], [IDL.Vec(CatalogItem)], ['query']),
    'getAllShopOrders' : IDL.Func([], [IDL.Vec(ShopOrder)], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCatalogItem' : IDL.Func([IDL.Nat], [IDL.Opt(CatalogItem)], ['query']),
    'getCustomerProfile' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'customerName' : IDL.Text,
              'deliveryAddress' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getMyShopOrders' : IDL.Func([IDL.Text], [IDL.Vec(ShopOrder)], ['query']),
    'getOrdersByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OrderRecord)],
        ['query'],
      ),
    'getPublishedCatalogItems' : IDL.Func(
        [],
        [IDL.Vec(CatalogItem)],
        ['query'],
      ),
    'getUpiSettings' : IDL.Func([], [IDL.Opt(UpiSettings)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeShopOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ShopOrderItem),
          IDL.Float64,
        ],
        [ShopOrder],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCustomerProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setBusinessInfo' : IDL.Func([BusinessInfo], [], []),
    'setUpiSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitOrderFull' : IDL.Func([ServiceOrder], [IDL.Nat], []),
    'togglePublishCatalogItem' : IDL.Func([IDL.Nat], [], []),
    'updateCatalogItem' : IDL.Func([IDL.Nat, CatalogItemInput], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateShopOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };