/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessInfo {
  'hours' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface CatalogItem {
  'id' : bigint,
  'requiredDocuments' : string,
  'stockStatus' : string,
  'requiresPdfCalc' : boolean,
  'published' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'price' : string,
  'mediaFiles' : Array<ExternalBlob>,
  'mediaTypes' : Array<string>,
}
export interface CatalogItemInput {
  'requiredDocuments' : string,
  'stockStatus' : string,
  'requiresPdfCalc' : boolean,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : string,
  'mediaFiles' : Array<ExternalBlob>,
  'mediaTypes' : Array<string>,
}
export type ExternalBlob = Uint8Array;
export interface FilterOrders {
  'status' : [] | [string],
  'serviceType' : [] | [string],
  'name' : [] | [string],
  'phone' : [] | [string],
}
export interface Inquiry {
  'name' : string,
  'message' : string,
  'phone' : string,
}
export interface KhataEntry {
  'customerName' : string,
  'lastUpdated' : bigint,
  'totalDue' : number,
  'phone' : string,
}
export interface MaskedShopOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'deliveryAddress' : string,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'deliveryMethod' : string,
  'totalAmount' : number,
  'phone' : string,
  'items' : Array<ShopOrderItem>,
}
export interface OrderRecord {
  'id' : bigint,
  'status' : string,
  'serviceType' : string,
  'name' : string,
  'submittedAt' : bigint,
  'instructions' : string,
  'uploadedFiles' : Array<ExternalBlob>,
  'phone' : string,
  'fileUrl' : string,
}
export interface PosSale {
  'id' : bigint,
  'paymentMethod' : string,
  'customerPhone' : string,
  'staffMobile' : string,
  'createdAt' : bigint,
  'totalAmount' : number,
  'items' : Array<PosSaleItem>,
}
export interface PosSaleItem {
  'qty' : bigint,
  'itemName' : string,
  'unitPrice' : number,
  'totalPrice' : number,
}
export interface Review {
  'id' : bigint,
  'customerName' : string,
  'deliveryRating' : [] | [bigint],
  'customerPhone' : string,
  'serviceRating' : bigint,
  'published' : boolean,
  'createdAt' : bigint,
  'orderId' : bigint,
  'location' : string,
  'deliveryComment' : [] | [string],
  'serviceComment' : string,
}
export interface Rider {
  'pin' : string,
  'name' : string,
  'role' : string,
  'mobile' : string,
}
export interface ServiceOrder {
  'files' : Array<ExternalBlob>,
  'serviceType' : string,
  'name' : string,
  'instructions' : string,
  'phone' : string,
}
export interface ShopOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'deliveryAddress' : string,
  'paymentMethod' : string,
  'deliveryOtp' : string,
  'cscFinalOutput' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'deliveryMethod' : string,
  'cscDocuments' : Array<ExternalBlob>,
  'cscSpecialDetails' : string,
  'totalAmount' : number,
  'phone' : string,
  'items' : Array<ShopOrderItem>,
}
export interface ShopOrderItem {
  'qty' : bigint,
  'itemId' : bigint,
  'itemName' : string,
  'price' : number,
}
export interface TypesettingQuoteRequest {
  'id' : bigint,
  'status' : string,
  'subject' : string,
  'name' : string,
  'submittedAt' : bigint,
  'language' : string,
  'quoteNotes' : string,
  'phone' : string,
  'finalPdfUrl' : string,
  'format' : string,
  'fileUrl' : string,
}
export interface TypesettingQuoteRequestInput {
  'subject' : string,
  'name' : string,
  'language' : string,
  'phone' : string,
  'format' : string,
  'fileUrl' : string,
}
export interface TypesettingQuoteUpdate { 'status' : string }
export interface UpiSettings { 'upiId' : string, 'qrCodeUrl' : string }
export interface UserProfile {
  'customerName' : [] | [string],
  'deliveryAddress' : [] | [string],
  'name' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCatalogItem' : ActorMethod<[CatalogItemInput], bigint>,
  'addKhataDue' : ActorMethod<[string, string, number], number>,
  'addRider' : ActorMethod<[string, string, string], undefined>,
  'addTeamMember' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminWithMasterKey' : ActorMethod<[string], boolean>,
  'clearKhataDue' : ActorMethod<[string, number], number>,
  'deductWallet' : ActorMethod<[string, number], number>,
  'deductWalletForOrder' : ActorMethod<[string, number], number>,
  'deleteCatalogItem' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'exportBulkLeadsToCsv' : ActorMethod<[], string>,
  'filterOrders' : ActorMethod<[FilterOrders], Array<OrderRecord>>,
  'generateOtp' : ActorMethod<[string], string>,
  'getAllCatalogItems' : ActorMethod<[], Array<CatalogItem>>,
  'getAllKhataEntries' : ActorMethod<[], Array<KhataEntry>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllTypesettingQuotes' : ActorMethod<[], Array<TypesettingQuoteRequest>>,
  'getBusinessInfo' : ActorMethod<[], BusinessInfo>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCatalogItem' : ActorMethod<[bigint], [] | [CatalogItem]>,
  'getCustomerProfile' : ActorMethod<
    [string],
    [] | [{ 'customerName' : string, 'deliveryAddress' : string }]
  >,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getKhataEntry' : ActorMethod<[string], [] | [KhataEntry]>,
  'getOrdersByPhone' : ActorMethod<[string], Array<OrderRecord>>,
  'getPosSales' : ActorMethod<[], Array<PosSale>>,
  'getPosSalesByPhone' : ActorMethod<[string], Array<PosSale>>,
  'getPublishedCatalogItems' : ActorMethod<[], Array<CatalogItem>>,
  'getPublishedReviews' : ActorMethod<[], Array<Review>>,
  'getReadyForDeliveryOrders' : ActorMethod<[], Array<MaskedShopOrder>>,
  'getRiders' : ActorMethod<[], Array<Rider>>,
  'getUpiSettings' : ActorMethod<[], [] | [UpiSettings]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[string], number>,
  'importBulkLeadsFromCsv' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderDelivered' : ActorMethod<[bigint, string], ShopOrder>,
  'placeCscShopOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<ShopOrderItem>,
      number,
      Array<ExternalBlob>,
      string,
    ],
    ShopOrder
  >,
  'placeShopOrder' : ActorMethod<
    [string, string, string, string, string, Array<ShopOrderItem>, number],
    ShopOrder
  >,
  'rechargeWallet' : ActorMethod<[string, number], number>,
  'recordPosSale' : ActorMethod<
    [Array<PosSaleItem>, number, string, string, string],
    bigint
  >,
  'removeRider' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCustomerProfile' : ActorMethod<[string, string, string], undefined>,
  'seedReviews' : ActorMethod<[], undefined>,
  'setBusinessInfo' : ActorMethod<[BusinessInfo], undefined>,
  'setUpiSettings' : ActorMethod<[string, string], undefined>,
  'submitInquiry' : ActorMethod<[string, string, string], undefined>,
  'submitOrder' : ActorMethod<[string, string, string, string, string], bigint>,
  'submitOrderFull' : ActorMethod<[ServiceOrder], bigint>,
  'submitReview' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      string,
      [] | [bigint],
      [] | [string],
    ],
    bigint
  >,
  'submitTypesettingQuoteRequest' : ActorMethod<
    [TypesettingQuoteRequestInput],
    bigint
  >,
  'togglePublishCatalogItem' : ActorMethod<[bigint], undefined>,
  'toggleReviewPublished' : ActorMethod<[bigint], undefined>,
  'updateCatalogItem' : ActorMethod<[bigint, CatalogItemInput], undefined>,
  'updateLeadFinalPdf' : ActorMethod<[bigint, string], undefined>,
  'updateLeadQuoteNotes' : ActorMethod<[bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateTypesettingQuoteStatus' : ActorMethod<
    [bigint, TypesettingQuoteUpdate],
    undefined
  >,
  'uploadCscFinalOutput' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'verifyBulkStaff' : ActorMethod<[string, string], boolean>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
  'verifyRider' : ActorMethod<[string, string], boolean>,
  'verifyStaff' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];